Shalev dev2
Tacitor/ENGG1420-FinalProj pull request #5
Opened 2023-03-18 17:56 UTC by Shalev001

all of the classes have been tested and function as expected

2023-03-22 23:19 UTC, Fluff-E approved these changes

2023-03-23 19:17 UTC, Tacitor requested changes
Please change the String to a StringBuilder in LocFile.java

Also if you don't mind adding stack traces to the catch statement print outs

2023-03-23 19:17 UTC, Tacitor commented on FileProcessor/src/main/java/com/group7/FileProcessor/entries/LocFile.java
> +            String temp = "";
Would you be able to use a StringBuilder for this?

2023-03-23 19:17 UTC, Tacitor commented on FileProcessor/src/main/java/com/group7/FileProcessor/entries/LocFile.java
> +            System.out.println("File Not Found, adress: " + address);
Could you add printing the stack trace to the print statement too? Might help debugging later.

2023-03-23 19:17 UTC, Tacitor commented on FileProcessor/src/main/java/com/group7/FileProcessor/entries/Local.java
> +            System.out.println("IOException in LocFile");
Again if you don't mind if you could print out the stack trace here too.

2023-03-27 01:28 UTC, Tacitor approved these changes
Looks great!

2023-03-27 01:28 UTC, merged